CREATE TABLE `env_project_investigate_rent_office` (
  `INVESTIGATE_ID` varchar(36) NOT NULL COMMENT '考察表的ID,与project_investigate_table中的ID组成外键关系', 
  CONTENT VARCHAR(500) NULL DEFAULT NULL COMMENT '补贴情况',
  SUBSIDY_AMOUNT INT NULL DEFAULT NULL COMMENT '应补贴金额,单位元',
  SUBSIDY_SQUARE INT NULL DEFAULT NULL COMMENT '补贴面积，单位平方米',
  START_DATE DATETIME NULL DEFAULT NULL COMMENT '补贴结束时间',
  END_DATE DATETIME NULL DEFAULT NULL COMMENT '补贴结束时间',
  LAW_NO  VARCHAR(500) NULL DEFAULT NULL COMMENT '补贴的法律文号',
  STANDARDIZATION  VARCHAR(500) NULL DEFAULT NULL COMMENT '补贴的法律文号',
  PRIMARY KEY (`INVESTIGATE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '场租补贴类项目考察信息表';
