CREATE TABLE `env_project_approval_loan_info` (
  `APPROVAL_ID` varchar(36) NOT NULL COMMENT '审批表ID',
  ACCOUNTANT_AMOUNT_OF_INTEREST DECIMAL(17,2) NULL DEFAULT NULL COMMENT '会计审计后的资助金额',
  TOTAL_LOAN DECIMAL(17,2) NULL DEFAULT NULL COMMENT '贷款总额',
  BANK_NAME VARCHAR(200) NULL DEFAULT NULL COMMENT '贷款银行',
  START_DATE DATETIME NULL DEFAULT NULL COMMENT '贷款开始日期',
  END_DATE DATETIME NULL DEFAULT NULL COMMENT '贷款介绍日期',
  INTEREST DECIMAL(17,2) NULL DEFAULT NULL COMMENT '贷款利息，在基准利率上浮后的百分点',
  LOW_BASIC_INTEREST DECIMAL(17,2) NULL DEFAULT NULL COMMENT '最低基准利率',
  HIGH_BASIC_INTEREST DECIMAL(17,2) NULL DEFAULT NULL COMMENT '最高基准利率',
  REAL_AMOUNT_OF_INTEREST_ DECIMAL(17,2) NULL DEFAULT NULL COMMENT '实际付息额',
  AUDIT_AMOUNT_OF_INTEREST_ DECIMAL(17,2) NULL DEFAULT NULL COMMENT '审定利息额',
  COMPANY_SCALE VARCHAR(200) NULL DEFAULT NULL COMMENT '企业规模',
  INTEREST_FACTOR DECIMAL(17,2) NULL DEFAULT NULL COMMENT '贴息系数',
  PRIMARY KEY (`APPROVAL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '银政企合作贴息';