CREATE TABLE `env_review_advanced_service` (
  `REVIEW_ID` varchar(36) NOT NULL COMMENT '评审表ID',
  IS_SERVICE_TYPE_QUALIFIED VARCHAR(100) NULL DEFAULT NULL COMMENT '服务业务是否符合',
  IS_CORPORATE_REPRESENTATIVEQUALIFIED VARCHAR(100) NULL DEFAULT NULL COMMENT '法人资格是否符合',
  IS_EMPLOYEE_AMOUNT_QUALIFIED VARCHAR(100) NULL DEFAULT NULL COMMENT '职工人数比例是否符合',
  IS_TECH_ADVANCED VARCHAR(100) NULL DEFAULT NULL COMMENT '技术先进是否符合',
  IS_INT_OUTSOURCE_QUALIFIED VARCHAR(100) NULL DEFAULT NULL COMMENT '国际外部是否符合',
  RD_ABLITY VARCHAR(200) NULL DEFAULT NULL COMMENT '研发能力,枚举，强、较强、弱三个选项',
  PRIMARY KEY (`REVIEW_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '技术先进型服务企业认定专家评审意见';
